<?xml version="1.0" encoding="utf-8"?><Database Name="DWKDB" Class="DWKDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ie0p1a01o5.database.windows.net;Initial Catalog=DWKDB;Persist Security Info=True;User ID=FP_User" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DWKDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="FP.UserView" Member="UserViews">
    <Type Name="UserView" Id="ID1">
      <Column Name="UserID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TransactionCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ButtonText" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PayeeName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NextPayeeName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GiftAmount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="FP.Setting_SelectByKey" Method="Setting_SelectByKey">
    <Parameter Name="Key" Parameter="key" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="Setting_SelectByKeyResult">
      <Column Name="Value" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="FP.User_Insert" Method="User_Insert">
    <Parameter Name="PayeeID" Parameter="payeeID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="NewUserID" Parameter="newUserID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(30)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="FP.User_Select" Method="User_Select">
    <Parameter Name="Key" Parameter="key" Type="System.String" DbType="VarChar(30)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="FP.User_Update" Method="User_Update">
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(20)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="FP.User_Customize" Method="User_Customize">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="ImageUrl" Parameter="imageUrl" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ButtonText" Parameter="buttonText" Type="System.String" DbType="VarChar(100)" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>