<?xml version="1.0" encoding="utf-8"?><Database Name="ph15822995272_BigButton" Class="DWKDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=198.71.226.2;Initial Catalog=ph15822995272_BigButton;Persist Security Info=True;User ID=BigButtonUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ph15822995272_BigButtonConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="BigButtonUser.UserView" Member="UserViews">
    <Type Name="UserView" Id="ID1">
      <Column Name="UserID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="PayeeID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PayeeName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TransactionCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClickCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastClickDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NextPayeeName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ServerTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="BigButtonUser.User_UpdateClickCounter" Method="User_UpdateClickCounter">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="BigButtonUser.User_Update" Method="User_Update">
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(30)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="BigButtonUser.User_Select" Method="User_Select">
    <Parameter Name="Key" Parameter="key" Type="System.String" DbType="VarChar(30)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="BigButtonUser.User_Insert" Method="User_Insert">
    <Parameter Name="PayeeID" Parameter="payeeID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="NewUserID" Parameter="newUserID" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(30)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="BigButtonUser.Setting_SelectByKey" Method="Setting_SelectByKey">
    <Parameter Name="Key" Parameter="key" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="Setting_SelectByKeyResult">
      <Column Name="Value" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>