#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakePyramid
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DWKDB")]
	public partial class DWKDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DWKDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DWKDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserView> UserViews
		{
			get
			{
				return this.GetTable<UserView>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="FP.User_Insert")]
		public int User_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="VarChar(30)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewUserID", DbType="VarChar(30)")] string newUserID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, newUserID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="FP.User_SelectByUserID")]
		public ISingleResult<UserView> User_SelectByUserID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="VarChar(30)")] string userID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
			return ((ISingleResult<UserView>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="FP.UserView")]
	public partial class UserView
	{
		
		private string _UserID;
		
		private string _ParentID;
		
		private string _PayeeID;
		
		private System.DateTime _JoinDateTime;
		
		private int _L1;
		
		private int _L2;
		
		private int _L3;
		
		private int _L4;
		
		private int _L5;
		
		public UserView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayeeID", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PayeeID
		{
			get
			{
				return this._PayeeID;
			}
			set
			{
				if ((this._PayeeID != value))
				{
					this._PayeeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinDateTime", DbType="DateTime NOT NULL")]
		public System.DateTime JoinDateTime
		{
			get
			{
				return this._JoinDateTime;
			}
			set
			{
				if ((this._JoinDateTime != value))
				{
					this._JoinDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L1", DbType="Int NOT NULL")]
		public int L1
		{
			get
			{
				return this._L1;
			}
			set
			{
				if ((this._L1 != value))
				{
					this._L1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L2", DbType="Int NOT NULL")]
		public int L2
		{
			get
			{
				return this._L2;
			}
			set
			{
				if ((this._L2 != value))
				{
					this._L2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L3", DbType="Int NOT NULL")]
		public int L3
		{
			get
			{
				return this._L3;
			}
			set
			{
				if ((this._L3 != value))
				{
					this._L3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L4", DbType="Int NOT NULL")]
		public int L4
		{
			get
			{
				return this._L4;
			}
			set
			{
				if ((this._L4 != value))
				{
					this._L4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L5", DbType="Int NOT NULL")]
		public int L5
		{
			get
			{
				return this._L5;
			}
			set
			{
				if ((this._L5 != value))
				{
					this._L5 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
